# src/services/search/vector_store.py
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import chromadb
from chromadb.config import Settings
from sentence_transformers import SentenceTransformer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class SearchResult:
    """A single result returned by VectorStore.search()."""
    doc_id: str
    content: str
    score: float                  # cosine similarity 0.0 – 1.0 (higher = more similar)
    metadata: Dict[str, Any]


# ---------------------------------------------------------------------------
# VectorStore
# ---------------------------------------------------------------------------

class VectorStore:
    """
    ChromaDB-backed vector store preserving CS2 evidence metadata.

    Stores embeddings generated by SentenceTransformer (all-MiniLM-L6-v2)
    alongside rich metadata for filtered retrieval:
        company_id, source_type, signal_category, dimension,
        dimension_weights, confidence, fiscal_year, source_url

    Usage:
        store = VectorStore()
        store.index_cs2_evidence(evidence_list, dimension_mapper)
        results = store.search("cloud data pipeline", company_id="NVDA", dimension="data_infrastructure")
    """

    def __init__(self, persist_dir: str = "./chroma_data") -> None:
        self.client = chromadb.PersistentClient(
            path=persist_dir,
            settings=Settings(anonymized_telemetry=False),
        )
        self.collection = self.client.get_or_create_collection(
            name="pe_evidence",
            metadata={"hnsw:space": "cosine"},
        )
        self.encoder = SentenceTransformer("all-MiniLM-L6-v2")
        logger.info("vector_store_initialized", extra={"persist_dir": persist_dir})

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index_cs2_evidence(
        self,
        evidence_list: List["CS2Evidence"],       # type: ignore[name-defined]
        dimension_mapper: "DimensionMapper",       # type: ignore[name-defined]
    ) -> int:
        """
        Index a list of CS2Evidence items into ChromaDB.

        For each evidence item:
        1. Gets dimension weights from DimensionMapper (CS3 signal→dimension map).
        2. Derives the primary dimension (highest weight).
        3. Encodes content with SentenceTransformer.
        4. Stores with full metadata for downstream filtered search.

        Returns the number of documents indexed.
        Skips duplicates — ChromaDB upsert behaviour handles re-indexing gracefully.
        """
        if not evidence_list:
            logger.warning("index_cs2_evidence_called_with_empty_list")
            return 0

        ids: List[str] = []
        contents: List[str] = []
        metadatas: List[Dict[str, Any]] = []

        for e in evidence_list:
            # Map CS2 signal category → CS3 dimension weights
            dim_weights = dimension_mapper.get_dimension_weights(e.signal_category)
            primary_dim = dimension_mapper.get_primary_dimension(e.signal_category)

            ids.append(e.evidence_id)
            contents.append(e.content)
            metadatas.append({
                "company_id": e.company_id,
                "source_type": e.source_type.value,
                "signal_category": e.signal_category.value,
                "dimension": primary_dim.value,
                "dimension_weights": str(dim_weights),   # stored as JSON string
                "confidence": e.confidence,
                "fiscal_year": e.fiscal_year or 0,
                "source_url": e.source_url or "",
            })

        # Encode all contents in one batch (faster than one-by-one)
        embeddings = self.encoder.encode(contents).tolist()

        self.collection.add(
            ids=ids,
            embeddings=embeddings,
            documents=contents,
            metadatas=metadatas,
        )

        logger.info(
            "cs2_evidence_indexed",
            extra={"count": len(ids)},
        )
        return len(ids)

    def index_documents(self, documents: List[Dict[str, Any]]) -> int:
        """
        Generic document indexing — used by AnalystNotesCollector and Airflow DAG.

        Each document dict must have:
            doc_id:   str
            content:  str
            metadata: dict (optional)

        Returns number of documents indexed.
        """
        if not documents:
            return 0

        ids = [d["doc_id"] for d in documents]
        contents = [d["content"] for d in documents]
        metadatas = [d.get("metadata", {}) for d in documents]

        embeddings = self.encoder.encode(contents).tolist()

        self.collection.add(
            ids=ids,
            embeddings=embeddings,
            documents=contents,
            metadatas=metadatas,
        )

        logger.info("documents_indexed", extra={"count": len(ids)})
        return len(ids)

    # ------------------------------------------------------------------
    # Search
    # ------------------------------------------------------------------

    def search(
        self,
        query: str,
        top_k: int = 10,
        company_id: Optional[str] = None,
        dimension: Optional[str] = None,
        source_types: Optional[List[str]] = None,
        min_confidence: float = 0.0,
    ) -> List[SearchResult]:
        """
        Semantic search with optional metadata filters.

        Args:
            query:          Natural language query string.
            top_k:          Number of results to return.
            company_id:     Filter to a specific company (e.g. "NVDA").
            dimension:      Filter to a specific CS3 dimension value
                            (e.g. "data_infrastructure").
            source_types:   Filter to specific CS2 source types
                            (e.g. ["sec_10k_item_1", "job_posting_linkedin"]).
                            Note: ChromaDB supports single-field $in filters only
                            at collection level; source_types filter is applied
                            post-retrieval when multiple types are provided.
            min_confidence: Minimum evidence confidence threshold (0.0 – 1.0).

        Returns:
            List of SearchResult ordered by cosine similarity descending.
        """
        # Build ChromaDB where clause (AND logic across fields)
        where: Dict[str, Any] = {}

        if company_id:
            where["company_id"] = company_id
        if dimension:
            where["dimension"] = dimension
        if min_confidence > 0.0:
            where["confidence"] = {"$gte": min_confidence}

        # source_types: use $in when single condition, else post-filter
        single_source = None
        if source_types and len(source_types) == 1:
            where["source_type"] = source_types[0]
            single_source = None
        elif source_types:
            single_source = set(source_types)   # will filter after retrieval

        # Combine multiple where conditions with $and if needed
        chroma_where = self._build_where(where) if where else None

        query_embedding = self.encoder.encode(query).tolist()

        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=top_k if not single_source else top_k * 3,  # over-fetch for post-filter
            where=chroma_where,
        )

        search_results = [
            SearchResult(
                doc_id=results["ids"][0][i],
                content=results["documents"][0][i],
                score=1 - results["distances"][0][i],   # cosine distance → similarity
                metadata=results["metadatas"][0][i],
            )
            for i in range(len(results["ids"][0]))
        ]

        # Post-filter for multiple source_types
        if single_source:
            search_results = [
                r for r in search_results
                if r.metadata.get("source_type") in single_source
            ][:top_k]

        return search_results

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_where(conditions: Dict[str, Any]) -> Dict[str, Any]:
        """
        Build a ChromaDB where clause.

        ChromaDB requires $and when multiple conditions are present.
        Single condition can be passed directly.
        """
        if len(conditions) == 1:
            return conditions
        # Wrap multiple conditions in $and
        return {"$and": [{k: v} for k, v in conditions.items()]}